[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

remappings = [
    "solmate/=lib/solmate/src/",
    "solmate-test/=lib/solmate/test/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
